config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'
  resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base
	validates_length_of :name, minimum: 5, maximum: 50, allow_blank: false
	validates_uniqueness_of :name

	validates_length_of :description, minimum: 15, maximum: 255, allow_blank: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def new
		@product = Product.new
	end
	
	def create
	  @product = Product.new(product_params)

	  if @product.save
	    redirect_to @product, notice: "Produto foi criado."
	  else
	    flash[:alert] = "Produto não pode ser criado."

	    render "new"
	  end
	end
	
	def show
  		@product = Product.find(params[:id])
	end

  private
    def product_params
      params.require(:product).permit(:name, :description)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_errors.html.erb
  <% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      O formulário contém <%= pluralize(object.errors.count, "erro") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>

app/views/layouts/_navbar.html.erb
	<nav>
		<div class="navbar navbar-inverse" role="navigation">
	      <div class="container">
	        <div class="navbar-header">
	          <a class="navbar-brand" href="#">Crud com RSPEC - Uhuu!</a>
	        </div>
	        <div class="collapse navbar-collapse">
	          <ul class="nav navbar-nav">
	            <li class="active"><a href="#">Início</a></li>
	            <li><a href="#about">Produtos</a></li>
	             <li><%= link_to 'Novo Produto', new_product_path %></li>
	          </ul>
	        </div>
	      </div>
	    </div>
	</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrudRspec</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render "layouts/navbar" %>
	<%= render "layouts/messages" %>
    <div class="container">
      <%= yield %>
    </div>
</body>
</html>

app/views/products/new.html.erb
<h2>New Product</h2>
  <%= form_for(@product) do |f| %>
    <%= render 'layouts/errors', object: f.object %>
      <p>
        <%= f.label :name%><br />
        <%= f.text_field :name %>
      </p>
      <p>
        <%= f.label :description, "Descrição" %><br />
        <%= f.text_field :description %>
      </p>
      <p>
         <%= f.submit "Criar Produto" %>
      </p>
  <% end %>

app/views/products/show.html.erb
<h2><%= @product.name %></h2>
<p><%= @product.description %></p>